/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.Timer;

/**
 *
 * @author Daniel Ortiz Vallejo
 */
public class VentanaJuego extends javax.swing.JFrame {

    static int ANCHOPANTALLA = 800;
    static int ALTOPANTALLA = 600;

    BufferedImage buffer = null;
    int contador = 0;
    Nave miNave = new Nave(ANCHOPANTALLA);
    Disparo miDisparo = new Disparo(ALTOPANTALLA);

    //Bucle de animacion del juego
    //En este caso es un hilo de ejecucion que se encarga
    //de la animacion del contenido
    Timer temporizador = new Timer(10, new ActionListener() {
	@Override
	public void actionPerformed(ActionEvent e) {
	    //TODO: Codigo de la animacion
	    bucleDelJuego();
	}
    });

    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
	initComponents();
	setSize(ANCHOPANTALLA, ALTOPANTALLA);
	buffer = (BufferedImage) jPanel1.createImage(ANCHOPANTALLA, ALTOPANTALLA);
	buffer.createGraphics();
	miNave.x = ANCHOPANTALLA / 2 - miNave.imagen.getWidth(this) / 2;
	miNave.y = ALTOPANTALLA - miNave.imagen.getHeight(this) - 35;
	//Inicio el temporizador
	temporizador.start();

    }

    private void bucleDelJuego() {
	//El bucle de animacion gobierna el redibujado de los objetos en el JPanel1
	//Primero borro todo lo que hay en buffer
	Graphics2D g2 = (Graphics2D) buffer.getGraphics();
	g2.setColor(Color.BLACK);
	g2.fillRect(0, 0, ANCHOPANTALLA, ALTOPANTALLA);

	////////////////////////////////////////////////////////////////////////
	//Redibujamos cada elemento en su nueva posicion en el buffer
	//Pintamos el disparo
	miDisparo.mueve();
	g2.drawImage(miDisparo.imagen, miDisparo.getX(), miDisparo.getY(), null);
	//Pintamos la nave
	miNave.mueve();
	g2.drawImage(miNave.imagen, miNave.x, miNave.y, null);
	////////////////////////////////////////////////////////////////////////

	//Redibujo el buffer sobre el JPanel
	g2 = (Graphics2D) jPanel1.getGraphics();
	g2.drawImage(buffer, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
	switch (evt.getKeyCode()) {
	    case KeyEvent.VK_SPACE:
		miDisparo.setDisparado(true);
		miDisparo.posicionaDisparo(miNave);
		break;
	    case KeyEvent.VK_RIGHT:
		miNave.setPulsadoDerecha(true);
		break;
	    case KeyEvent.VK_D:
		miNave.setPulsadoDerecha(true);
		break;
	    case KeyEvent.VK_LEFT:
		miNave.setPulsadoIzquierda(true);
		break;
	    case KeyEvent.VK_A:
		miNave.setPulsadoIzquierda(true);
		break;
	}
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
	switch (evt.getKeyCode()) {
	    case KeyEvent.VK_RIGHT:
		miNave.setPulsadoDerecha(false);
		break;
	    case KeyEvent.VK_D:
		miNave.setPulsadoDerecha(false);
		break;
	    case KeyEvent.VK_LEFT:
		miNave.setPulsadoIzquierda(false);
		break;
	    case KeyEvent.VK_A:
		miNave.setPulsadoIzquierda(false);
		break;
	}
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new VentanaJuego().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
